//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentisOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int idAppointment { get; set; }
        public string Treatment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<bool> Reminder { get; set; }
        public Nullable<int> idPatient { get; set; }
        public string Comment { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
