//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentisOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public Balance()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int idBalance { get; set; }
        public Nullable<int> idPatient { get; set; }
        public Nullable<decimal> Balance1 { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
