//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentisOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicalStory
    {
        public ClinicalStory()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int idClinicalStory { get; set; }
        public string CurrentCondition { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
