//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentisOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Balances = new HashSet<Balance>();
        }
    
        public int idPatient { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNumber { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Folder { get; set; }
        public Nullable<int> PreferredContactForm { get; set; }
        public Nullable<int> idClinicalStory { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> UserRegistration { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Balance> Balances { get; set; }
        public virtual ClinicalStory ClinicalStory { get; set; }
    }
}
