//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentisOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int idPayment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Pay { get; set; }
        public Nullable<int> idBalance { get; set; }
    
        public virtual Balance Balance { get; set; }
    }
}
